remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

name: Eric's Portfolio
title: Data Science Portfolio - Eric Perides Mattos
description: [A portfolio containing my data science projects]
